# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(-90, -110, 991, 731))
        self.background.setStyleSheet("QLabel {\n"
"    background-image: url(\"C:/Users/Alexander/Pictures/work/1/background1.png\");\n"
"\n"
"}")
        self.background.setText("")
        self.background.setObjectName("background")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 50, 391, 91))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"\n"
"    color: white;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.start_bt = QtWidgets.QPushButton(self.centralwidget)
        self.start_bt.setGeometry(QtCore.QRect(250, 240, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.start_bt.setFont(font)
        self.start_bt.setStyleSheet("QPushButton {\n"
"    background-color: lightblue;\n"
"    border-radius:  10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"\n"
"}")
        self.start_bt.setObjectName("start_bt")
        self.circle1 = QtWidgets.QPushButton(self.centralwidget)
        self.circle1.setGeometry(QtCore.QRect(20, 240, 90, 90))
        self.circle1.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    border-radius: 45px; \n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: darkred\n"
"}")
        self.circle1.setText("")
        self.circle1.setObjectName("circle1")
        self.circle2 = QtWidgets.QPushButton(self.centralwidget)
        self.circle2.setGeometry(QtCore.QRect(380, 420, 90, 90))
        self.circle2.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    border-radius: 45px; \n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: darkred\n"
"}")
        self.circle2.setText("")
        self.circle2.setObjectName("circle2")
        self.circle4 = QtWidgets.QPushButton(self.centralwidget)
        self.circle4.setGeometry(QtCore.QRect(560, 250, 90, 90))
        self.circle4.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    border-radius: 45px; \n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: darkred\n"
"}")
        self.circle4.setText("")
        self.circle4.setObjectName("circle4")
        self.circle5 = QtWidgets.QPushButton(self.centralwidget)
        self.circle5.setGeometry(QtCore.QRect(120, 310, 90, 90))
        self.circle5.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    border-radius: 45px; \n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: darkred\n"
"}")
        self.circle5.setText("")
        self.circle5.setObjectName("circle5")
        self.circle3 = QtWidgets.QPushButton(self.centralwidget)
        self.circle3.setGeometry(QtCore.QRect(630, 350, 90, 90))
        self.circle3.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    border-radius: 45px; \n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: darkred\n"
"}")
        self.circle3.setText("")
        self.circle3.setObjectName("circle3")
        self.click_info = QtWidgets.QLabel(self.centralwidget)
        self.click_info.setGeometry(QtCore.QRect(24, 25, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.click_info.setFont(font)
        self.click_info.setStyleSheet("QLabel {\n"
"    color: white;\n"
"\n"
"}")
        self.click_info.setObjectName("click_info")
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setGeometry(QtCore.QRect(530, 20, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.info_label.setFont(font)
        self.info_label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"\n"
"}")
        self.info_label.setObjectName("info_label")
        self.time_left = QtWidgets.QLabel(self.centralwidget)
        self.time_left.setGeometry(QtCore.QRect(680, 20, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.time_left.setFont(font)
        self.time_left.setStyleSheet("QLabel {\n"
"    color: white;\n"
"\n"
"}")
        self.time_left.setText("")
        self.time_left.setObjectName("time_left")
        self.click_on = QtWidgets.QLabel(self.centralwidget)
        self.click_on.setGeometry(QtCore.QRect(120, 20, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.click_on.setFont(font)
        self.click_on.setStyleSheet("QLabel {\n"
"    color: white;\n"
"\n"
"}")
        self.click_on.setText("")
        self.click_on.setObjectName("click_on")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "AIM TRAINING"))
        self.start_bt.setText(_translate("MainWindow", "START"))
        self.click_info.setText(_translate("MainWindow", "Click:"))
        self.info_label.setText(_translate("MainWindow", "time left:"))
